services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - mynetwork
      - mynetwork2

  api:
    build: ./api
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  chat-world:
    image: nginx:latest
    volumes:
      - ./chat-world:/usr/share/nginx/html:ro
    networks:
      - mynetwork

  chat-private:
    image: nginx:latest
    volumes:
      - ./chat-private:/usr/share/nginx/html:ro
    networks:
      - mynetwork2

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.8.6.0/24"
          gateway: "10.8.6.1"

  mynetwork2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.8.7.0/24"
          gateway: "10.8.7.1"